# ----- Stage 1: builder -----
FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# ----- Stage 2: runtime -----
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
RUN addgroup -S app && adduser -S pippo -G app
COPY --from=builder /app/target/devops-app-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
USER pippo
CMD ["java","-jar","app.jar"]